apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodeapp
  name: my-nodeapp
  namespace: shrutitest
spec:
  ports:
  - name: https
    nodePort: 30334
    port: 3000
    protocol: TCP
    targetPort: 8080
  selector:
    app: nodeapp
  sessionAffinity: None
  type: LoadBalancer
